demo/assets/location-list.json, demo/index.html, tangy-form-condensed-editor.js, tangy-form-editor.js, test/index.html, test/tangy-box-widget_test.html, test/tangy-checkboxes-widget_test.html, test/tangy-radio-buttons-widget_test.html, widget/tangy-box-widget.js, widget/tangy-checkbox-widget.js, widget/tangy-checkboxes-widget.js, widget/tangy-date-widget.js, widget/tangy-gps-widget.js, widget/tangy-location-widget.js, widget/tangy-number-widget.js, widget/tangy-radio-buttons-widget.js, widget/tangy-select-widget.js, widget/tangy-text-widget.js, widget/tangy-time-widget.js, widget/tangy-timed-widget.js
Added other tests to test/index.html
Minor test tweaks
=> Implemented tangy-box-widget

tangy-base-widget.js, tangy-form-editor-add-input.js, widget/tangy-box-widget.js, widget/tangy-checkbox-widget.js, widget/tangy-checkboxes-widget.js, widget/tangy-date-widget.js, widget/tangy-eftouch-widget.js, widget/tangy-gps-widget.js, widget/tangy-location-widget.js, widget/tangy-number-widget.js, widget/tangy-radio-buttons-widget.js, widget/tangy-select-widget.js, widget/tangy-text-widget.js, widget/tangy-time-widget.js, widget/tangy-timed-widget.js
Added descriptions of each input element.
=> Created highlight property on base

package-lock.json, tangy-base-widget.js, tangy-form-condensed-editor.js, tangy-form-editor-reducer.js, tangy-form-editor.js, test/tangy-form-condensed-editor_test.html, test/tangy-form-editor_test.html, test/tangy-text-widget_test.html, widget/tangy-text-widget.js
=> Add print mode

tangy-form-editor.js, tangy-form-item-editor.js, widget/tangy-box-widget.js, widget/tangy-checkbox-widget.js, widget/tangy-checkboxes-widget.js, widget/tangy-date-widget.js, widget/tangy-email-widget.js, widget/tangy-gps-widget.js, widget/tangy-location-widget.js, widget/tangy-number-widget.js, widget/tangy-radio-buttons-widget.js, widget/tangy-select-widget.js, widget/tangy-text-generic-widget.js, widget/tangy-text-widget.js, widget/tangy-time-widget.js, widget/tangy-timed-widget.js
Related to:
- https://github.com/Tangerine-Community/Tangerine/issues/1317
- https://github.com/Tangerine-Community/Tangerine/issues/1185
=> #1185 escape double quotes in onchange onopen

widget/tangy-timed-widget.js
* Allow editors to edit the`auto-stop` attribute
* Closes * Closes Tangerine-Community/Tangerine#1269
* exposed the `autoStop` property to the editor interface for `tangy-timed`
=> Add autostop attribute to tangy-timed

demo/assets/translation.json, demo/index.html, package-lock.json, package.json, tangy-form-editor.js, tangy-form-item-editor.js, test/tangy-form-editor_test.html, test/tangy-form-item-editor_test.html
Most strings now use the t function, except for tangy-base-widget
=> Implemented tangy-translate and translation.json for demo

demo/index.html, tangy-base-widget.js, tangy-form-condensed-editor.js, tangy-form-editor.js, tangy-form-item-editor.js, widget/tangy-box-widget.js, widget/tangy-checkbox-widget.js, widget/tangy-checkboxes-widget.js, widget/tangy-date-widget.js, widget/tangy-eftouch-widget.js, widget/tangy-email-widget.js, widget/tangy-gps-widget.js, widget/tangy-location-widget.js, widget/tangy-number-widget.js, widget/tangy-qr-widget.js, widget/tangy-radio-buttons-widget.js, widget/tangy-select-widget.js, widget/tangy-template-widget.js, widget/tangy-text-widget.js, widget/tangy-time-widget.js, widget/tangy-timed-widget.js, widget/tangy-untimed-grid-widget.js
* Made changes to the visuals of various elements
* Used CSS variables across components
* Standardized look and feel
* Example css variables that should be set are:
```css
*{
--accent-color:#f26f10;
--accent-text-color:white;
--lighter-accent-color: #ff9522;
--primary-color: #3c5b8d;
--primary-color-dark: #3c5b8d;
--primary-color-lighter: #2d7dd2;
}
```
=> UI improvements from design mock up

demo/files.json, demo/index.html, package.json, tangy-form-condensed-editor.js, tangy-form-editor-add-input.js, tangy-form-editor.js, tangy-form-item-editor.js, widget/tangy-eftouch-widget-layout.js, widget/tangy-eftouch-widget.js
Place a `files-endpoint` attribute on `<tangy-form-editor>` and that will get passed down the to the `<file-list-select>` elements in the EF Touch widget.
=> Implement usage of endpoint and file-list-select element for selecting files.

package.json, tangy-form-condensed-editor.js, tangy-form-editor-add-input.js, widget/tangy-partial-date-widget.js
Added support for tangy partial date.
=> Add tangy partial date widget

tangy-form-html-editor.js
Show warning message when user is editing HTML
* Closes Tangerine-Community/Tangerine#1565
=> Show warning message when user is editing HTML

tangy-form-item-editor.js
* Make threshold input element to be shown in edit mode
* Closes Tangerine-Community/Tangerine#1590
=> Make threshold input element to be shown in edit mode

widget/tangy-select-widget.js
This is configurable in translation file:  '----':'-- Select One --'
=> Removed secondaryLabel

tangy-form-editor-reducer.js, tangy-form-editor.js
* Fixes https://github.com/Tangerine-Community/Tangerine/issues/2109
=> Allow for duplication of  entire section

tangy-form-editor.js
* Allow for setting `cycle-sequences`
* Fixes https://github.com/Tangerine-Community/Tangerine/issues/1603
* Part of https://github.com/Tangerine-Community/tangy-form/pull/212
=> Cycle Sequences

tangy-form-editor.js, tangy-form-item-editor.js
This is for issue [#1021](https://github.com/Tangerine-Community/Tangerine/issues/1021)
=> WIP: Scoring section

widget/tangy-video-capture-widget.js
Refs Tangerine-Community/Tangerine#3400
=> feat(tangy-video-capture): Add option to record audio when using `tangy-video-capture

tangy-form-editor.js, tangy-form-item-editor.js
For issue [#1021](https://github.com/Tangerine-Community/Tangerine/issues/1021)
=> Persist scoring

widget/tangy-video-capture-widget.js
Part of Tangerine-Community/tangy-form#363 and #333
Refs Tangerine-Community/Tangerine#3400
=> fix((scope ?)): Allow editor to choose whether to record audio during video recording

demo/index.html, tangy-form-condensed-editor.js, tangy-form-editor-add-input.js, widget/tangy-ethio-date-widget.js
Adds the tangy-ethio-date widget to tangy-form-editor so it is available in authoring and issues
=> Add ethiopian date widget to tangy-form-editor

tangy-form-editor-reducer.js
Refs:
1. Tangerine-Community/Tangerine#2109
2. Tangerine-Community/Tangerine#2565
3. Tangerine-Community/Tangerine#3433
4. https://github.com/Tangerine-Community/tangy-form-editor/pull/173
=> fix(copying-sections): Copy sections including the contents

tangy-form-editor.js
Closes https://github.com/Tangerine-Community/tangy-form/issues/267
=> fix(cycle-sequences): User defined Cycle Sequences index should begin at 1

package-lock.json, package.json, widget/tangy-video-capture-widget.js
Refs Tangerine-Community/Tangerine#3400
=> fix(video-capture): Allow users to toggle record-audio and persist the changes

tangy-form-editor-reducer.js
Ensure only top level items are copied with their contents
Refs:
1. Tangerine-Community/Tangerine#2109
2. Tangerine-Community/Tangerine#2565
3. Tangerine-Community/Tangerine#3433
4. https://github.com/Tangerine-Community/tangy-form-editor/pull/173
=> fix(section-copy): Copy sections including the contents

tangy-form-item-editor.js
Refs #Tangerine-Community/Tangerine#3442
=> fix(custom-scring): reflect properties to attribute and offload custom script evaluation to client

tangy-form-editor.js
Refs Tangerine-Community/Tangerine#3441
=> fix(tangy-editor): Full Screen Nav Buttons alignment

tangy-form-editor.js
Refs Tangerine-Community/Tangerine#3442
=> fix(custom-scoring): Add editing on reopen
